name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./tictactoe-frontend

      - name: Run tests
        run: npm run test
        working-directory: ./tictactoe-frontend

      - name: Build
        run: npm run build
        working-directory: ./tictactoe-frontend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create stack
        run: |
          pulumi up -s dev -y
          echo "BUCKET_NAME=$(pulumi stack -s dev output bucketName)" >> $GITHUB_ENV
        working-directory: ./tictactoe-frontend
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}