name: learn-github-actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Set git user email
        run: git config --global user.email "jennifer.lucifero@codecentric.de"
      - name: set git user name
        run: git config --global user.name "Jennifer Lucifero"
      - name: set remote repo
        run: git remote set-url origin git@github.com:missjennbo/tictactoe-react.git
      - name: Build project
        run: npm run build
      - name: Deploy app
        run: npm run deploy