name: Deploy Frontend
on: [push]
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install and build
        run: |
          npm install
          npm run build