name: Build and deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: check-code
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup node
      - uses: actions/setup-node@v1

      - name: Install and build
        run: |
          npm install
          npm run build

      - name: Deploy app
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch