name: Test code
on: [push]
jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test